import { type App, type Lock, type SourceConfig, verifyLock } from "./schema.ts";
import { json } from "./workspace.ts";

export function renderSource(source: SourceConfig, apps: App[], lock: Lock) {
  verifyLock(apps, lock);
  return {
    ...source,
    apps: apps.map(({ id, manifest }) => {
      const {
        checkver: _checkver,
        autoupdate: _autoupdate,
        releaseNotes: _releaseNotes,
        ...metadata
      } = manifest;
      const entry = lock.apps[id]!;
      const version = entry.version;
      return {
        ...metadata,
        versions: [version],
        appPermissions: entry.appPermissions,
        // A few sideloading clients still consume the original flat source fields.
        version: version.version,
        versionDate: version.date,
        versionDescription: version.localizedDescription,
        downloadURL: version.downloadURL,
        size: version.size,
      };
    }),
    news: [],
  };
}

const escape = (value: string) =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("|", "&#124;")
    .replaceAll("[", "&#91;")
    .replaceAll("]", "&#93;")
    .replaceAll("`", "&#96;")
    .replaceAll("{", "&#123;")
    .replaceAll("}", "&#125;")
    .replaceAll("\n", " ");

export function renderCatalog(
  source: SourceConfig,
  apps: App[],
  lock: Lock,
  locale: "en" | "zh" = "en",
): string {
  verifyLock(apps, lock);
  const rows = apps.map(({ id, manifest }) => {
    const entry = lock.apps[id]!;
    const v = entry.version;
    return `| [${escape(manifest.name)}](https://github.com/${manifest.checkver.github}) | ${v.version} (${escape(v.buildVersion)}) | ${v.minOSVersion} | ${(v.size / 1024 / 1024).toFixed(1)} MiB | [IPA](${v.downloadURL}) |`;
  });
  if (locale === "zh") {
    return `<!-- Generated by bucket-cli build. -->\n\n# 应用目录\n\n在 SideStore 或 AltStore Classic 中添加[此软件源](${source.sourceURL})。\n\n每个应用仅发布最新的稳定版本。\n\n| 应用 | 版本（构建） | 最低 iOS 版本 | 下载大小 | 下载 |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n\n本软件源直接链接到上游发布文件，不会重新托管或签名 IPA。\n`;
  }
  return `<!-- Generated by bucket-cli build. -->\n\n# Apps\n\nAdd [this source](${source.sourceURL}) in SideStore or AltStore Classic.\n\nOnly the latest stable version of each app is published.\n\n| App | Version (build) | Minimum iOS | Download size | Download |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n\nThe source links directly to upstream releases. IPA files are not rehosted or re-signed.\n`;
}

export function artifacts(source: SourceConfig, apps: App[], lock: Lock): Record<string, string> {
  return {
    "apps.json": json(renderSource(source, apps, lock)),
    "docs/apps.md": renderCatalog(source, apps, lock),
    "docs/zh/apps.md": renderCatalog(source, apps, lock, "zh"),
  };
}
